### ISSUE TITLE
2001025215084 will give 2020-10-25 (today is 2020-10-04) instead of 1920-10-25

### ISSUE THREAD

**Issue by emahuni** [dale-french/south-african-id-validator#3]
I think this lib should take into consideration the following rules

- id is eligible to 16 years and above, meaning current year - 16 is the limit at which we can safely say the year is a 21st century year, anything else is more than a century old  (helps with very very old ID numbers)
- it should also check if the month and day are not future dates, as much as it is checking the year

going to create a PR soon

**Comment by dale-french** [comment]
Thanks @emahuni - I have merged #4 and #5 and released `v1.1.0` to npm.
